---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.copsds.com
  resources:
  - encryptedsecrets
  - generatedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.copsds.com
  resources:
  - encryptedsecrets/finalizers
  - generatedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - security.copsds.com
  resources:
  - encryptedsecrets/status
  - generatedsecrets/status
  verbs:
  - get
  - patch
  - update
