apiVersion: security.copsds.com/v1alpha1
kind: GeneratedSecret
metadata:
  labels:
    app.kubernetes.io/name: encrypted-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: generatedsecret-sample 
  namespace: encrypted-secret-operator-system
spec:
  # Tipo di segreto da generare (es. "password", "token", "keypair")
  type: "keypair"

  # Endpoint API generazione
  endpoint: 
    protocol: "grpc"
    address: "vault-mock-grpc-svc.vault-mock.svc.cluster.local:9000"
    insecure: true

  # Parametri generazione per coppia di chiavi RSA
  parameters:
    algorithm: "AES"
    keySize: "256"
    format: "BASE64"

  # Trigger evento
  trigger:
    onCreate: true
    onRotate: true
    onSpecChange: false
    schedule: ""

  # Rotazione automatica mensile
  rotationInterval: "30d"

  # Versioni da mantenere
  maxVersions: 5