apiVersion: security.copsds.com/v1alpha1
kind: EncryptedSecret
metadata:
  labels:
    app.kubernetes.io/name: encrypted-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: encryptedsecret-sample
spec:
  # TODO(user): Add fields here
