apiVersion: security.copsds.com/v1alpha1
kind: EncryptedSecret
metadata:
  labels:
    app.kubernetes.io/name: encrypted-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: encryptedsecret-sample
spec:
  data:
    username: "admin"
    password: "SuperSecret123!"
  cryptoEndpoint: "https://crypto-service.example.com/encrypt"
  rotationInterval: "24h"
  ttl: "168h"
  maxVersions: 3
  restartTargets:
    - deployment/example-app
